import { getServerSession } from "next-auth";
import { NextResponse } from "next/server";
import { z } from "zod";
import { adminAuthOptions } from "@/lib/auth/admin-options";
import { orderInclude, serializeOrder, toDeliveryStatus, toOrderStatus } from "@/lib/admin/order-db";
import { prisma } from "@/lib/db/prisma";
type Context = { params: Promise<{ id: string }> };
const schema = z.object({ orderStatus: z.enum(["Pending","Confirmed","Processing","Delivered","Cancelled"]).optional(), deliveryStatus: z.enum(["Not Scheduled","Scheduled","Preparing","Out for Delivery","Delivered","Delivery Failed","Rescheduled","Cancelled"]).optional(), cancellationReason: z.string().max(100).optional(), cancellationNotes: z.string().max(500).optional() }).refine((value) => Object.keys(value).length > 0);
export async function GET(_: Request, { params }: Context) { const session = await getServerSession(adminAuthOptions); if (!session?.user?.id) return NextResponse.json({ message: "Unauthorized." }, { status: 401 }); const order = await prisma.order.findUnique({ where: { id: (await params).id }, include: orderInclude }); return order ? NextResponse.json(serializeOrder(order)) : NextResponse.json({ message: "Order not found." }, { status: 404 }); }
export async function PATCH(request: Request, { params }: Context) { const session = await getServerSession(adminAuthOptions); if (!session?.user?.id) return NextResponse.json({ message: "Unauthorized." }, { status: 401 }); const parsed = schema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ message: parsed.error.issues[0]?.message ?? "Invalid update." }, { status: 400 }); const { id } = await params; const existing = await prisma.order.findUnique({ where: { id } }); if (!existing) return NextResponse.json({ message: "Order not found." }, { status: 404 }); if (existing.orderStatus === "DELIVERED" && parsed.data.orderStatus && parsed.data.orderStatus !== "Delivered") return NextResponse.json({ message: "A delivered order cannot be moved backwards." }, { status: 409 }); const cancelling = parsed.data.orderStatus === "Cancelled" || Boolean(parsed.data.cancellationReason); const order = await prisma.order.update({ where: { id }, data: { orderStatus: cancelling ? "CANCELLED" : parsed.data.orderStatus ? toOrderStatus(parsed.data.orderStatus) : undefined, deliveryStatus: cancelling ? "CANCELLED" : parsed.data.deliveryStatus ? toDeliveryStatus(parsed.data.deliveryStatus) : undefined, cancellationReason: parsed.data.cancellationReason, cancellationNotes: parsed.data.cancellationNotes, cancelledAt: cancelling ? new Date() : undefined }, include: orderInclude }); return NextResponse.json(serializeOrder(order)); }
